### ISSUE TITLE
使用正则时，回复貌似不会解析cq码，能修改成可以解析吗

### ISSUE THREAD

**Issue by hurttttr** [lgc2333/nonebot-plugin-autoreply#17]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply/assets/58456022/af79f3ae-a863-4e3e-8b36-8ccca078b6a5)
```
- 
  matches:
    -
      match: '^(.+?)\1+$'
      type: regex
  replies:
    - '{v0}{v1}'
```
这是我的配置，想要自动对重复内容+1并回复，但目前表情有些问题
